# Demo configuration for testing video penibility assessment
# This config uses dummy paths for demonstration purposes

experiment:
  name: "demo_experiment"
  seed: 42
  output_dir: "results/demo"
  device: "auto"
  log_level: "INFO"
  tags: ["demo", "test"]

data:
  annotation_path: "dummy_data.csv"  # Will be created for demo
  features_type: "i3d"
  data_type: "full_body"
  target_normalization: false
  max_timesteps: null
  features_root: "data/features"

model:
  name: "gru"
  hidden_dim: 64
  num_layers: 1
  output_dim: 1
  dropout: 0.1

training:
  batch_size: 8
  learning_rate: 0.001
  weight_decay: 0.01
  num_epochs: 5
  early_stopping_patience: 10

cross_validation:
  n_splits: 3
  strategy: "subject_wise"

visualization:
  save_plots: true
  show_plots: false 