# Configuration for I3D features with GRU model
# Equivalent to: python train_features_seq.py --features_type i3d --model_name gru --data_type full_body --n_splits 5 --lr 0.001 --num_epochs 150 --batch_size 16

experiment:
  name: "i3d_gru"
  seed: 42
  output_dir: "results/i3d_gru"
  device: "cuda:0"
  log_level: "INFO"
  tags: ["i3d", "gru", "full_body"]

data:
  annotation_path: "/mnt/user_disk/skhazem/storage_1_10T/ai_vision_share/data/labels/annotation_skeewai_v2.csv"
  features_root: "/mnt/user_disk/skhazem/storage_1_10T/ai_vision_share/features"
  features_type: "i3d"
  data_type: "full_body"
  target_normalization: false
  max_timesteps: null

model:
  name: "gru"
  hidden_dim: 512
  num_layers: 2
  output_dim: 1
  dropout: 0.1
  extra_params: {}

training:
  batch_size: 16
  learning_rate: 0.001
  weight_decay: 0.01
  num_epochs: 150
  early_stopping_patience: 30
  optimizer: "adamw"
  loss_function: "mse"
  metrics: ["mse", "mae", "r2", "ccc"]
  save_best_model: true
  scheduler: null
  scheduler_params: {}

cross_validation:
  n_splits: 5
  strategy: "subject_wise"
  random_state: 42

visualization:
  save_plots: true
  show_plots: false 