# Configuration equivalent to original command:
# python src/dl_video/train_features_seq.py --features_type swin3d_t --model_name transformer --data_type full_body --n_splits 5 --lr 0.001 --num_epochs 150 --batch_size 16 --device cuda:0

experiment:
  name: "swin3d_transformer_custom"
  seed: 42
  output_dir: "results/swin3d_transformer"
  device: "cuda:0"
  log_level: "INFO"
  tags: ["swin3d_t", "transformer", "full_body"]

data:
  annotation_path: "/mnt/user_disk/skhazem/storage_1_10T/ai_vision_share/data/labels/annotation_skeewai_v2.csv"
  features_root: "/mnt/user_disk/skhazem/storage_1_10T/ai_vision_share/features"
  features_type: "swin3d_t"                 # Type of features (swin3d_t as in original command)
  data_type: "full_body"                    # Data type (full_body as in original command)
  target_normalization: false
  max_timesteps: null                       # Maximum timesteps (null for no limit)

model:
  name: "transformer"
  hidden_dim: 512
  num_heads: 8
  num_layers: 2
  output_dim: 1
  dropout: 0.1
  extra_params: {}

training:
  batch_size: 16                           # As in original command
  learning_rate: 0.001                     # As in original command
  weight_decay: 0.01
  num_epochs: 150                          # As in original command
  early_stopping_patience: 30
  optimizer: "adamw"
  loss_function: "mse"
  metrics: ["mse", "mae", "r2", "ccc"]
  save_best_model: true
  scheduler: null
  scheduler_params: {}

cross_validation:
  n_splits: 5                              # As in original command
  strategy: "subject_wise"
  random_state: 42

visualization:
  save_plots: true
  show_plots: false 