# Configuration equivalent to original command but with demo data:
# python src/dl_video/train_features_seq.py --features_type swin3d_t --model_name transformer --data_type full_body --n_splits 5 --lr 0.001 --num_epochs 150 --batch_size 16 --device cuda:0

experiment:
  name: "swin3d_transformer_demo"
  seed: 42
  output_dir: "results/transformer_demo"
  device: "cuda:0"
  log_level: "INFO"
  tags: ["swin3d_t", "transformer", "full_body", "demo"]

data:
  annotation_path: "dummy_data.csv"                                                       # Using dummy data for demo
  features_root: "/mnt/user_disk/skhazem/storage_1_10T/ai_vision_share/features"         # Real features directory
  features_type: "i3d"               # Type of features to load (i3d, swin3d_t, etc.)
  data_type: "full_body"             # Data type (full_body, face_1.7, etc.)
  target_normalization: false
  max_timesteps: null                # Maximum timesteps (null for no limit)

model:
  name: "transformer"
  hidden_dim: 512
  num_heads: 8
  num_layers: 2
  output_dim: 1
  dropout: 0.1

training:
  batch_size: 16
  learning_rate: 0.001
  weight_decay: 0.01
  num_epochs: 10  # Shorter for demo
  early_stopping_patience: 30
  optimizer: "adamw"
  loss_function: "mse"
  metrics: ["mse", "mae", "r2", "ccc"]
  save_best_model: true

cross_validation:
  n_splits: 3  # Smaller for demo
  strategy: "subject_wise"

visualization:
  save_plots: true
  show_plots: false 